import { registerPhrases } from './i18n'

const phrases: Record<string, string> = {
  '任务面板': 'Task panel',
  '面板视图': 'Panel views',
  '文件': 'Files',
  '终端': 'Terminal',
  '浏览器': 'Browser',
  '摘要': 'Summary',
  '变更': 'Changes',
  '拖出为独立窗口': 'Pop out to a separate window',
  '拖出为独立置顶窗口': 'Pop out to an always-on-top window',
  '收起右栏': 'Collapse panel',
  '选择或新建任务后显示任务摘要': 'Select or create a task to see its summary',
  '选择或新建任务后显示文件变更': 'Select or create a task to see file changes',
  '请先选择项目': 'Select a project first',
  '文件浏览仅在桌面应用中可用': 'File browsing is only available in the desktop app',
  '返回目录': 'Back to directory',
  '文件过大，仅显示前 400 KB': 'File too large — showing the first 400 KB only',
  '上一级': 'Up one level',
  '刷新': 'Refresh',
  '（空目录）': '(Empty directory)',
  '错误：{msg}': 'Error: {msg}',
  '终端仅在桌面应用中可用': 'The terminal is only available in the desktop app',
  '在项目根目录': 'Run a command in the project root',
  '执行命令，输出显示在这里。': ', and its output appears here.',
  '运行中…': 'Running…',
  '输入命令，Enter 执行': 'Type a command, press Enter to run',
  '终端命令': 'Terminal command',
  '执行命令': 'Run',
  '\n  位置：{loc}': '\n  at: {loc}',
  '请帮我修复以下浏览器控制台报错（页面：{page}）：': 'Please help me fix the following browser console error (page: {page}):',
  '请帮我修复以下 {n} 条浏览器控制台报错（页面：{page}）：': 'Please help me fix the following {n} browser console errors (page: {page}):',
  '输入网址': 'Enter a URL',
  '网址': 'URL',
  '在系统浏览器打开': 'Open in system browser',
  '内嵌浏览器与控制台日志捕获仅在桌面应用中可用。': 'The embedded browser and console log capture are only available in the desktop app.',
  '输入网址后回车加载': 'Enter a URL and press Enter to load',
  '加载页面': 'Load page',
  '输入本地预览地址（如 http://localhost:3000）后回车，页面控制台日志会显示在下方，可一键添加到对话让 AI 修复。': 'Enter a local preview URL (e.g. http://localhost:3000) and press Enter. Console logs appear below and can be added to the chat for the AI to fix in one click.',
  '控制台': 'Console',
  '只看报错': 'Errors only',
  '清空日志': 'Clear logs',
  '把所有报错添加到对话': 'Add all errors to the chat',
  '添加全部报错': 'Add all errors',
  '暂无日志': 'No logs yet',
  '加载页面后，控制台日志会显示在这里。': 'Console logs will appear here once a page is loaded.',
  '添加到对话': 'Add to chat',
  '未运行': 'Stopped',
  '连接中': 'Connecting',
  '已连接': 'Connected',
  '连接失败': 'Connection failed',
  '{n} 个工具': '{n} tool(s)',
  '任务待办': 'Task to-dos',
  '全部待办已完成': 'All to-dos completed',
  '待办': 'To-dos',
  '回复正文中出现的待办会显示在这里。': 'To-dos found in the reply appear here.',
  '上下文用量': 'Context usage',
  '约 {used} / {total} tokens': '~{used} / {total} tokens',
  '发送一轮对话后显示用量': 'Usage shows after a reply',
  '压缩上下文': 'Compact context',
  '移除较早的消息以释放上下文': 'Remove older messages to free up context',
  '上下文使用超过 70% 后可压缩': 'Available once context usage exceeds 70%',
  '压缩上下文失败，请重试。': 'Failed to compact context, please try again.',
  '弹出为独立窗口': 'Pop out to a separate window',
  '弹出为独立置顶窗口': 'Pop out to an always-on-top window',
  '重新加载': 'Reload',
  '重试': 'Retry',
  '无法访问该地址': 'Unable to reach this address',
  '页面加载失败（{code}）：{desc}': 'Page failed to load ({code}): {desc}',
  '隐藏控制台': 'Hide console',
  '显示控制台': 'Show console',
  '回到中心': 'Recenter',
  '回到画布中心（第一个模块处）': 'Back to canvas center (first module)',
  '完整的接口列表、Work 模式模块扩展与 MCP 说明见项目根目录的 plugins.md 开发文档。': 'See plugins.md in the project root for the full interface list, Work-mode module extension, and MCP notes.',
  '本轮回复已完成': 'This reply is complete',
  '正在处理…': 'Working…',
  '联网搜索': 'Web search',
  '联网搜索到的网页会显示在这里。可在设置 → 插件中开启联网搜索。': 'Web pages from search appear here. Enable web search under Settings → Plugins.',
  '上下文': 'Context',
  '尚未引用上下文': 'No context referenced yet',
  '读写文件': 'Files read/written',
  '尚未读写文件': 'No files read or written yet',
  '工具': 'Tools',
  '尚未调用工具': 'No tools called yet',
  '插件': 'Plugins',
  '尚未启用插件，可在设置 → 插件中开启': 'No plugins enabled — turn them on under Settings → Plugins',
  '尚未配置 MCP 服务器，可在设置 → MCP 中添加': 'No MCP servers configured — add one under Settings → MCP',
  '本任务尚未修改文件。写入或编辑后，改动会在这里按文件列出并高亮显示。': 'This task has not modified any files yet. Once you write or edit, changes are listed per file and highlighted here.',
  '执行': 'Execute',
  '检查': 'Check',
  '审阅': 'Review',
  '备注': 'Note',
  '电脑操控': 'Computer control',
  '浏览器操控': 'Browser control',
  '打开应用': 'Open app',
  '命令执行': 'Run command',
  '搜索定位': 'Search & locate',
  '文件读写': 'File read/write',
  'Git 提交': 'Git commit',
  '插件调用': 'Call plugin',
  'MCP 调用': 'Call MCP',
  '等待确认': 'Wait for confirmation',
  '询问用户': 'Ask the user',
  '让 Cubex 完成一项具体工作': 'Have Cubex complete a concrete piece of work',
  '运行测试或构建，验证前面步骤的结果': 'Run tests or a build to verify the results of previous steps',
  '总结并自查前面步骤的产出': 'Summarize and review the output of previous steps',
  '仅作为背景信息，不会被执行': 'Background information only — never executed',
  '截屏、输入文字、按键或点击屏幕坐标': 'Take screenshots, type text, press keys, or click screen coordinates',
  '打开网页并提取标题、正文与链接': 'Open a web page and extract its title, body, and links',
  '启动指定的应用、文件或网址': 'Launch a specified app, file, or URL',
  '在项目根目录运行 shell 命令': 'Run a shell command in the project root',
  '在项目文件中搜索或列出目录': 'Search project files or list a directory',
  '读取、创建或编辑项目文件': 'Read, create, or edit project files',
  '提交并推送改动到 GitHub 仓库': 'Commit and push changes to a GitHub repository',
  '调用已安装的插件完成特定任务': 'Call an installed plugin to perform a specific task',
  '调用已连接的 MCP 服务器工具': 'Call a tool from a connected MCP server',
  '确认外部条件就绪后再继续': 'Continue only after confirming an external condition is ready',
  '向用户提问以确认关键信息': 'Ask the user to confirm key information',
  '功能开发': 'Feature development',
  '问题排查': 'Troubleshooting',
  '代码审查': 'Code review',
  '理解需求': 'Understand the requirements',
  '阅读项目结构和相关代码，明确要实现的功能与边界条件。': 'Read the project structure and related code to clarify the feature to build and its edge cases.',
  '制定方案': 'Plan the approach',
  '列出实现步骤与涉及的文件，说明关键取舍。': 'List the implementation steps and files involved, explaining key trade-offs.',
  '编码实现': 'Implement',
  '按方案完成修改，保持与现有代码风格一致。': 'Make the changes per the plan, keeping consistent with the existing code style.',
  '验证': 'Verify',
  '运行测试与构建，修复出现的问题。': 'Run tests and the build, fixing any issues that arise.',
  '自查总结': 'Self-review & summary',
  '回顾所有修改，确认满足需求并总结变更点。': 'Review all changes, confirm they meet the requirements, and summarize what changed.',
  '复现问题': 'Reproduce the issue',
  '根据描述复现问题，记录触发条件与现象。': 'Reproduce the issue from the description, noting the trigger conditions and symptoms.',
  '定位根因': 'Find the root cause',
  '沿调用链排查，找到问题的根本原因并说明依据。': 'Trace the call chain to find the root cause and explain the reasoning.',
  '修复问题': 'Fix the issue',
  '实施最小且安全的修复，避免引入新问题。': 'Apply a minimal, safe fix without introducing new problems.',
  '回归验证': 'Regression check',
  '重新执行复现步骤并运行相关测试，确认问题已解决。': 'Re-run the reproduction steps and related tests to confirm the issue is resolved.',
  '梳理改动': 'Review the changes',
  '列出最近改动的文件与主要内容。': 'List the recently changed files and their main contents.',
  '逐项审查': 'Review item by item',
  '检查正确性、安全性、性能与代码风格问题。': 'Check for correctness, security, performance, and code style issues.',
  '输出报告': 'Write the report',
  '汇总发现的问题，按严重程度排序并给出修复建议。': 'Summarize the issues found, sort them by severity, and give fix suggestions.',
  '实现并验证': 'Implement and verify',
  '阅读项目结构和相关文件，总结需要完成的工作。': 'Read the project structure and related files to summarize the work to be done.',
  '根据上一步的结论完成修改，并运行测试或构建验证。': 'Make the changes based on the previous step, then run tests or a build to verify.',
  '工作流 {n}': 'Workflow {n}',
  '放弃未保存的修改': 'Discard unsaved changes',
  '当前工作流有未保存的修改，切换后将丢失。': 'This workflow has unsaved changes that will be lost if you switch.',
  '放弃修改': 'Discard',
  '单个工作流最多 20 个节点': 'A workflow can have at most 20 nodes',
  '{label}节点': '{label} node',
  '这条连线会形成循环，工作流需要是单向的': 'This connection would create a cycle — workflows must be one-directional',
  '单个工作流最多 60 条连线': 'A workflow can have at most 60 connections',
  '已按执行顺序自动排版': 'Auto-arranged by execution order',
  '请填写工作流名称': 'Please enter a workflow name',
  '工作流已保存': 'Workflow saved',
  '保存工作流失败，请重试。': 'Failed to save the workflow. Please try again.',
  '至少需要一个可执行节点（备注节点不会被执行）': 'At least one executable node is required (note nodes are never run)',
  '还有节点没有填写内容': 'Some nodes have no content yet',
  '运行工作流': 'Run workflow',
  '将依次执行「{name}」的 {n} 个节点，确定开始？': 'This will run the {n} node(s) of “{name}” in sequence. Start now?',
  '运行': 'Run',
  '已在后台开始运行，可在「AI 对话」中查看进度': 'Started running in the background — track progress under “AI Chat”',
  '运行工作流失败，请重试。': 'Failed to run the workflow. Please try again.',
  '删除工作流': 'Delete workflow',
  '确定删除「{name}」？此操作无法撤销。': 'Delete “{name}”? This cannot be undone.',
  '删除': 'Delete',
  '删除工作流失败，请重试。': 'Failed to delete the workflow. Please try again.',
  '空白工作流': 'Blank workflow',
  '模板：{name}': 'Template: {name}',
  '{label}节点 · {hint}': '{label} node · {hint}',
  '先选择一个项目': 'Select a project first',
  '工作流属于项目，打开项目后即可在画布上编排多步任务。': 'Workflows belong to a project. Open a project to orchestrate multi-step tasks on the canvas.',
  '工作流': 'Workflows',
  '未保存': 'Unsaved',
  '新建工作流': 'New workflow',
  '新建工作流（可选模板）': 'New workflow (template optional)',
  '工作流名称': 'Workflow name',
  '画布工具': 'Canvas tools',
  '撤销': 'Undo',
  '撤销（Ctrl+Z）': 'Undo (Ctrl+Z)',
  '重做': 'Redo',
  '重做（Ctrl+Y）': 'Redo (Ctrl+Y)',
  '自动排版': 'Auto layout',
  '按执行顺序自动排版': 'Auto-arrange by execution order',
  '适配视图': 'Fit to view',
  '缩放至完整显示': 'Zoom to fit',
  '缩小': 'Zoom out',
  '重置缩放': 'Reset zoom',
  '放大': 'Zoom in',
  '节点': 'Node',
  '保存': 'Save',
  '运行后自动切换到 AI 对话页查看进度': 'Switch to the AI Chat page to track progress after running',
  '切到对话': 'Switch to chat',
  '用画布编排多步任务': 'Orchestrate multi-step tasks on a canvas',
  '把复杂工作拆成节点，用连线决定先后顺序，一键交给 Cubex 依次执行。': 'Break complex work into nodes, use connections to set the order, and let Cubex run them in sequence with one click.',
  '连接到 {title}': 'Connect to {title}',
  '连接到此节点': 'Connect to this node',
  '输入': 'Input',
  '点击填写内容…': 'Click to add content…',
  '从 {title} 连线': 'Draw a connection from {title}',
  '拖出连线：点击后再点击目标节点左侧圆点': 'Draw a connection: click here, then click the dot on the left of the target node',
  '节点属性': 'Node properties',
  '节点设置': 'Node settings',
  '关闭': 'Close',
  '类型': 'Type',
  '节点类型': 'Node type',
  '标题': 'Title',
  '备注内容': 'Note content',
  '指令': 'Instruction',
  '写下要让 Cubex 参考的背景信息…': 'Write background information for Cubex to reference…',
  '描述这一步要让 Cubex 完成什么…': 'Describe what Cubex should do in this step…',
  '复制': 'Duplicate',
  '工作流概览': 'Workflow overview',
  '{n} 个节点': '{n} node(s)',
  '{n} 条连线': '{n} connection(s)',
  '{n} 条备注': '{n} note(s)',
  '使用说明': 'How to use',
  '拖动节点标题栏调整位置，Delete 删除选中节点': 'Drag a node’s title bar to move it; press Delete to remove the selected node',
  '点击节点右侧圆点，再点击目标节点左侧圆点即可连线': 'Click the dot on a node’s right, then the dot on the target node’s left to connect them',
  '点击连线可删除，Esc 取消连线，Ctrl+Z 撤销': 'Click a connection to delete it; press Esc to cancel linking, Ctrl+Z to undo',
  '备注节点不执行，仅作为背景信息提供给 Cubex': 'Note nodes are not executed — they only provide background information to Cubex',
  '运行时按连线顺序（无依赖时从左到右）依次执行': 'At runtime, nodes run in connection order (left to right when there are no dependencies)',
}

const settingsPhrases: Record<string, string> = {
  '不能为空或过小': 'Cannot be empty or too small',
  '超出允许长度或范围': 'Exceeds the allowed length or range',
  '请填写有效的值': 'Please enter a valid value',
  '格式不正确': 'Invalid format',
  '添加': 'Add',
  '移除规则 {rule}': 'Remove rule {rule}',
  '暂无规则': 'No rules yet',
  '全局 {value}': 'Global {value}',
  '{label}模型参数': '{label} model parameters',
  '温度': 'Temperature',
  '{label}温度': '{label} temperature',
  '全局：模型默认': 'Global: model default',
  '模型默认': 'Model default',
  '最大输出 Token': 'Max output tokens',
  '{label}最大输出 Token': '{label} max output tokens',
  '请求超时（秒）': 'Request timeout (seconds)',
  '{label}请求超时': '{label} request timeout',
  '失败重试次数': 'Retry count on failure',
  '{label}失败重试次数': '{label} retry count on failure',
  '上下文消息条数': 'Context message count',
  '{label}上下文消息条数': '{label} context message count',
  '已推送到 {repo}（{branch}）：{url}': 'Pushed to {repo} ({branch}): {url}',
  '复制失败，请手动选择下方文本复制。': 'Copy failed. Please select and copy the text below manually.',
  '背景图片过大（超过 10MB），请更换。': 'The background image is too large (over 10MB). Please choose another.',
  '背景图片读取失败，请重试。': 'Failed to read the background image. Please try again.',
  '新自动化': 'New automation',
  '新提供商': 'New provider',
  '新模型': 'New model',
  '请先修正提供商或模型中标红的字段': 'Please fix the highlighted fields in the provider or model first',
  '界面语言': 'Interface language',
  '应用界面显示使用的语言': 'The language used for the app interface',
  '回复语言': 'Reply language',
  '助手回复与说明使用的语言': 'The language used for the assistant’s replies and explanations',
  '回复风格': 'Reply style',
  '控制解释的详细程度': 'Controls how detailed explanations are',
  '主题': 'Theme',
  '配色方案': 'Color scheme',
  '强调色与语义色': 'Accent and semantic colors',
  '自定义背景': 'Custom background',
  '选择本地图片作为背景，并调节透明度让文字保持清晰': 'Choose a local image as the background and adjust its opacity to keep text readable',
  '更换图片': 'Replace image',
  '选择图片': 'Choose image',
  '移除背景': 'Remove background',
  '背景不透明度 {percent}%': 'Background opacity {percent}%',
  '已归档项目': 'Archived projects',
  '归档的项目不会出现在左侧列表，恢复后即可继续使用': 'Archived projects do not appear in the left list; restore them to continue using them',
  '审批模式': 'Approval mode',
  '修改文件或执行命令前是否需要你确认': 'Whether your confirmation is required before modifying files or running commands',
  '只读模式': 'Read-only mode',
  '禁止写入文件与执行命令，只允许阅读和搜索': 'Disallow writing files and running commands; only reading and searching are allowed',
  '沙箱执行': 'Sandboxed execution',
  '默认开启：命令在受限环境中运行，工作目录锁定在项目内、清理环境变量并拦截可能越权的命令': 'On by default: commands run in a restricted environment with the working directory locked to the project, environment variables cleaned, and potentially over-privileged commands blocked',
  '沙箱内允许联网': 'Allow network access in the sandbox',
  '关闭时沙箱内禁止网络访问，npm install / git clone 等联网命令会失败；仅在开启沙箱时生效': 'When off, network access is blocked in the sandbox and commands like npm install / git clone will fail; only effective when the sandbox is enabled',
  '自动允许的命令': 'Auto-allowed commands',
  '命中后无需审批即可执行，如 npm test、git status；支持 * 通配': 'Matching commands run without approval, e.g. npm test, git status; supports * wildcards',
  '如 npm run lint': 'e.g. npm run lint',
  '禁止的命令': 'Denied commands',
  '命中后一律拒绝，优先级高于允许列表；支持 * 通配': 'Matching commands are always rejected, taking priority over the allow list; supports * wildcards',
  '如 git push --force': 'e.g. git push --force',
  '删除前确认': 'Confirm before deleting',
  '删除任务或移除项目前弹出确认': 'Prompt for confirmation before deleting a task or removing a project',
  'MCP 服务器': 'MCP servers',
  '通过 Model Context Protocol 接入外部工具': 'Connect external tools via the Model Context Protocol',
  '提供商与模型': 'Providers and models',
  'OpenAI 兼容接口、Anthropic 或本机 Ollama；每个模型可展开“高级”覆盖参数': 'OpenAI-compatible APIs, Anthropic, or local Ollama; each model can expand “Advanced” to override parameters',
  '全局默认参数': 'Global default parameters',
  '未在模型“高级”中单独设置时使用': 'Used when not set individually under a model’s “Advanced”',
  '全局': 'Global',
  '已安装插件': 'Installed plugins',
  '内置浏览器与电脑控制插件，以及插件目录中你自己编写的插件；启用后其工具会提供给模型': 'Built-in browser and computer-control plugins, plus your own plugins in the plugins directory; once enabled, their tools are provided to the model',
  '编写插件': 'Write a plugin',
  '在插件目录中新建文件夹，放入 plugin.json 与入口脚本即可': 'Create a new folder in the plugins directory and add a plugin.json and an entry script',
  '每个插件是插件目录下的一个文件夹：': 'Each plugin is a folder under the plugins directory: ',
  ' 声明 name、description、version 与 tools，每个工具包含 name、description、command（如 ': ' declares name, description, version, and tools; each tool includes name, description, and command (e.g. ',
  '、': ', ',
  '）和可选的 parameters（JSON Schema）。': ') and optional parameters (JSON Schema).',
  '调用时在插件文件夹中执行 command：参数以 JSON 通过标准输入和环境变量 ': 'When called, the command runs in the plugin folder: arguments are passed as JSON via stdin and the environment variable ',
  ' 传入，': '; ',
  ' 为工具名，': ' is the tool name, ',
  ' 为当前项目根目录；标准输出即返回给模型的结果，单次最长 120 秒。': ' is the current project root; stdout is returned to the model as the result, up to 120 seconds per call.',
  '插件目录为空时会生成示例插件 hello 供参考。插件调用需要审批（完全自动模式除外），修改插件后点击“刷新”重新加载。': 'A sample plugin “hello” is generated for reference when the plugins directory is empty. Plugin calls require approval (except in fully automatic mode); after editing a plugin, click “Refresh” to reload.',
  '访问令牌': 'Access token',
  '需要 repo 权限的 Personal Access Token；通过系统加密保存在本机': 'A Personal Access Token with repo permission; stored locally with system encryption',
  'GitHub 访问令牌': 'GitHub access token',
  '已保存，输入新令牌可替换': 'Saved — enter a new token to replace it',
  'ghp_… 或 github_pat_…': 'ghp_… or github_pat_…',
  '验证并保存': 'Verify and save',
  '清除': 'Clear',
  '已连接：{login}': 'Connected: {login}',
  '未配置令牌时，模型不会获得推送工具': 'Without a token configured, the model does not get the push tool',
  '目标仓库': 'Target repository',
  '留空则使用项目文件夹名；仓库不存在时自动创建': 'Leave blank to use the project folder name; the repository is created automatically if it does not exist',
  '用户名/仓库名 或 仓库名': 'owner/repo or repo',
  '推送分支': 'Push branch',
  '新建仓库设为私有': 'Make new repositories private',
  '允许 AI 自动推送': 'Allow the AI to push automatically',
  '开启后模型完成阶段性改动时会主动提交并推送；关闭时仅在你明确要求时推送': 'When on, the model commits and pushes on its own after completing incremental changes; when off, it only pushes when you explicitly ask',
  '立即推送': 'Push now',
  '使用已保存的设置把所选项目提交并推送一次': 'Commit and push the selected project once using the saved settings',
  '要推送的项目': 'Project to push',
  '暂无项目': 'No projects',
  '推送': 'Push',
  '请先保存访问令牌': 'Please save the access token first',
  '请先保存设置更改': 'Please save your setting changes first',
  '推送前会自动初始化 Git 仓库并提交全部改动（遵循 .gitignore）': 'Before pushing, the Git repository is initialized automatically and all changes are committed (respecting .gitignore)',
  '自动化任务': 'Automation tasks',
  '应用运行期间按间隔或在每天/每周的指定时间，在指定项目中新建任务并发送指令；错过的定时会在应用下次运行时补跑一次；保存设置后生效': 'While the app is running, create a task and send instructions in a specified project at an interval or at a set daily/weekly time; missed schedules are run once the next time the app starts; effective after saving settings',
  '运行后切换到 AI 对话': 'Switch to AI Chat after running',
  '在 Work 模式运行工作流时自动跳转到对应会话查看进度；关闭则留在画布，在后台运行': 'When running a workflow in Work mode, automatically jump to the corresponding session to view progress; when off, stay on the canvas and run in the background',
  '运行工作流前确认': 'Confirm before running a workflow',
  '点击运行时先弹出确认，避免误触': 'Prompt for confirmation when you click Run to avoid accidental triggers',
  '操控时显示提示条': 'Show a banner during control',
  '电脑或浏览器被自动操控时，在界面顶部显示醒目提示条': 'Show a prominent banner at the top of the interface while the computer or browser is being controlled automatically',
  '按 Esc 结束操控': 'Press Esc to end control',
  '操控进行中按 Esc 立即请求停止电脑/浏览器操控': 'Press Esc during control to immediately request stopping computer/browser control',
  '启用提示音': 'Enable sounds',
  '任务状态变化时播放轻提示音（使用系统音频，无需额外文件）': 'Play a soft sound when a task’s status changes (uses system audio, no extra files needed)',
  '完成时提示音': 'Sound on completion',
  '回复完成时播放': 'Plays when a reply completes',
  '等待审批提示音': 'Sound when awaiting approval',
  '需要你确认命令或改动时播放': 'Plays when your confirmation of a command or change is required',
  '等待输入提示音': 'Sound when awaiting input',
  '模型向你提问、等待回复时播放': 'Plays when the model asks you a question and waits for a reply',
  '提示音音量': 'Sound volume',
  '命令 Shell': 'Command shell',
  '执行命令使用的终端': 'The terminal used to run commands',
  '命令超时': 'Command timeout',
  '单条命令最长执行时间，5–1800 秒': 'Maximum execution time for a single command, 5–1800 seconds',
  '秒': 'sec',
  '改动后自动验证': 'Auto-verify after changes',
  '修改代码后运行测试、类型检查或构建': 'Run tests, type checks, or a build after modifying code',
  '项目上下文文件': 'Project context files',
  '项目根目录的 goal.md、plan.md、memory.md、agents.md 会自动注入系统提示并在任务推进时实时更新': 'The project root’s goal.md, plan.md, memory.md, and agents.md are automatically injected into the system prompt and updated in real time as the task progresses',
  '打开新项目或项目中缺少这四个文件时会自动创建；已存在则原样作为参考。助手每完成一个阶段会更新 plan.md 与 memory.md，你也可以直接在项目中手动编辑。': 'These four files are created automatically when you open a new project or when they are missing; if they exist, they are used as-is for reference. The assistant updates plan.md and memory.md after each stage, and you can also edit them manually in the project.',
  '复杂任务先给计划': 'Plan first for complex tasks',
  '多步骤任务先列出简短计划再动手': 'For multi-step tasks, list a short plan before starting',
  '复杂任务自动生成待办': 'Auto-generate to-dos for complex tasks',
  '除简单问答外，动手前先拆成待办清单并逐项完成，防止长任务中途丢失进度': 'Except for simple Q&A, break the work into a to-do list and complete it item by item before starting, to avoid losing progress midway through long tasks',
  '单轮最多步数': 'Max steps per turn',
  '模型连续调用工具的上限，1–200': 'The limit on consecutive tool calls by the model, 1–200',
  '步': 'steps',
  '从其他 app 中继续未完成的工作': 'Continue unfinished work from another app',
  '复制下方提示词，在原来的 AI 应用里发送，让它把项目交接资料写入四个上下文文件，然后在 CubexDesktop 中打开该项目即可续接': 'Copy the prompt below and send it in your original AI app to have it write the project handoff materials into the four context files, then open the project in CubexDesktop to continue',
  '已复制': 'Copied',
  '复制交接提示词': 'Copy handoff prompt',
  '界面字体': 'Interface font',
  '整体界面字体风格': 'The overall interface font style',
  '界面字号': 'Interface font size',
  '代码字号': 'Code font size',
  '工具输出与差异的字号，11–18': 'Font size for tool output and diffs, 11–18',
  '界面密度': 'Interface density',
  '减少动效': 'Reduce motion',
  '关闭过渡与动画': 'Turn off transitions and animations',
  '显示 Token 用量': 'Show token usage',
  '在每条回复下方显示输入 / 输出 Token 数': 'Show input/output token counts below each reply',
  '默认展开工具输出': 'Expand tool output by default',
  '自动滚动到最新消息': 'Auto-scroll to the latest message',
  '完成时系统通知': 'System notification on completion',
  '窗口不在前台时，回复完成或等待审批会发送通知': 'When the window is not in the foreground, send a notification when a reply completes or approval is awaited',
  '发送方式': 'Send method',
  '常用快捷键': 'Common shortcuts',
  '编程优先的本地智能体桌面应用': 'A coding-first local agent desktop app',
  '系统提示词由应用内置，会根据语言、风格、审批、权限与工作树设置自动组合，无需手动维护。': 'The system prompt is built into the app and is composed automatically from the language, style, approval, permission, and worktree settings — no manual maintenance needed.',
  'API Key 通过系统加密保存在本机，不会写入配置文件；会话与设置保存在本机用户数据目录。': 'API keys are stored locally with system encryption and are never written to config files; sessions and settings are stored in the local user data directory.',
  '没有已归档的项目。在左侧项目菜单中选择“归档”后会出现在这里。': 'No archived projects. Choose “Archive” in the left project menu and they will appear here.',
  '恢复中…': 'Restoring…',
  '恢复': 'Restore',
  '{count} / 20 · 以 stdio 方式启动本地进程，保存后自动连接': '{count} / 20 · Starts a local process via stdio and connects automatically after saving',
  '刷新状态': 'Refresh status',
  '添加服务器': 'Add server',
  '还没有 MCP 服务器。例如添加命令 npx、参数 -y 与 @modelcontextprotocol/server-filesystem 及目录路径，即可让模型使用其工具。': 'No MCP servers yet. For example, add the command npx with the arguments -y and @modelcontextprotocol/server-filesystem plus a directory path to let the model use its tools.',
  '已停用': 'Disabled',
  '未保存': 'Unsaved',
  '未命名服务器': 'Unnamed server',
  '未设置启动命令': 'No start command set',
  ' · {count} 个工具': ' · {count} tool(s)',
  '有错误': 'Has errors',
  '名称': 'Name',
  '启动命令': 'Start command',
  '如 npx、uvx、node、python': 'e.g. npx, uvx, node, python',
  '参数（每行一个）': 'Arguments (one per line)',
  '参数': 'Arguments',
  '环境变量（每行 KEY=VALUE）': 'Environment variables (KEY=VALUE per line)',
  '环境变量': 'Environment variables',
  '正在启动并握手…': 'Starting and handshaking…',
  '已连接，但该服务器没有提供工具。': 'Connected, but this server provides no tools.',
  '启用 MCP 服务器 {name}': 'Enable MCP server {name}',
  '已启用': 'Enabled',
  '测试连接': 'Test connection',
  '启用的服务器工具会通过 mcp_call 提供给模型；除完全自动模式外，每次调用都需要你批准。': 'Enabled server tools are provided to the model via mcp_call; except in fully automatic mode, every call requires your approval.',
  '{count} 个': '{count}',
  '加载中…': 'Loading…',
  '打开插件目录': 'Open plugins directory',
  '正在读取插件…': 'Reading plugins…',
  '内置': 'Built-in',
  '自定义': 'Custom',
  '加载失败': 'Failed to load',
  '启用插件 {name}': 'Enable plugin {name}',
  '电脑控制可以截屏、输入和点击，每一步都会请求你批准。': 'Computer control can take screenshots, type, and click; each step requests your approval.',
}

const appPhrases: Record<string, string> = {
  '正在打开工作区…': 'Opening workspace…',
  '正在加载…': 'Loading…',
  '窗口控制': 'Window controls',
  '最小化': 'Minimize',
  '关闭': 'Close',
  '该任务已被删除，可以关闭此窗口。': 'This task has been deleted. You can close this window.',
  '无法读取工作区，请重新打开应用。': 'Unable to read the workspace. Please reopen the app.',
  '切换主题失败，请重试。': 'Failed to switch theme. Please try again.',
  '「{title}」等待你的审批': '"{title}" is waiting for your approval',
  '「{title}」需要你补充信息': '"{title}" needs more information from you',
  '「{title}」已完成回复': '"{title}" has finished replying',
  '系统通知发送失败，可在设置中关闭完成通知。': 'Failed to send a system notification. You can disable completion notifications in Settings.',
  '无法打开项目选择窗口，请重试。': 'Unable to open the project picker. Please try again.',
  '请先在设置中添加提供商与模型。': 'Please add a provider and model in Settings first.',
  '已加入队列，当前回复结束后自动发送': 'Queued — it will be sent automatically after the current reply finishes',
  '消息未能发送，请重试。': 'Failed to send the message. Please try again.',
  '回答未能提交，请重试。': 'Failed to submit your answer. Please try again.',
  '移除排队消息失败，请重试。': 'Failed to remove the queued message. Please try again.',
  '无法打开文件选择窗口，请重试。': 'Unable to open the file picker. Please try again.',
  '部分图片过大（超过 10MB）或读取失败，已忽略。': 'Some images were too large (over 10MB) or failed to load and were ignored.',
  '已添加到对话输入框': 'Added to the chat input',
  '切换审批模式失败，请重试。': 'Failed to switch approval mode. Please try again.',
  '停止失败，请重试。': 'Failed to stop. Please try again.',
  '删除任务': 'Delete Task',
  '确定删除任务「{title}」？对话记录将无法恢复，项目文件不受影响。': 'Delete task "{title}"? The conversation history cannot be recovered, but project files are unaffected.',
  '删除失败，请重试。': 'Failed to delete. Please try again.',
  '任务已删除': 'Task deleted',
  '重新生成失败，请重试。': 'Failed to regenerate. Please try again.',
  '回退对话': 'Roll Back Conversation',
  '将删除这条消息及其之后的所有内容，回到发送前的状态，无法恢复。': 'This will delete this message and everything after it, reverting to the state before it was sent. This cannot be undone.',
  '回退': 'Roll back',
  '回退失败，请重试。': 'Failed to roll back. Please try again.',
  '已回退': 'Rolled back',
  '删除消息': 'Delete Message',
  '确定删除这条消息？无法恢复。': 'Delete this message? This cannot be undone.',
  '消息已删除': 'Message deleted',
  '重命名任务': 'Rename Task',
  '任务名称': 'Task name',
  '重命名失败，请重试。': 'Failed to rename. Please try again.',
  '移除项目': 'Remove Project',
  '确定从 Cubex 中移除「{name}」及其 {count} 个任务？本地文件夹不会被删除。': 'Remove "{name}" and its {count} task(s) from Cubex? The local folder will not be deleted.',
  '确定从 Cubex 中移除「{name}」？本地文件夹不会被删除。': 'Remove "{name}" from Cubex? The local folder will not be deleted.',
  '移除': 'Remove',
  '移除项目失败，请重试。': 'Failed to remove the project. Please try again.',
  '项目已移除': 'Project removed',
  '重命名项目': 'Rename Project',
  '仅修改在 Cubex 中显示的名称，不会改动文件夹。': 'Only the name shown in Cubex is changed; the folder is not affected.',
  '归档失败，请重试。': 'Failed to archive. Please try again.',
  '已归档「{name}」，可在设置中恢复': 'Archived "{name}". You can restore it in Settings.',
  '新建任务': 'New Task',
  '在资源管理器中打开': 'Open in File Explorer',
  '无法打开文件夹。': 'Unable to open the folder.',
  '复制路径': 'Copy Path',
  '路径已复制': 'Path copied',
  '复制失败': 'Copy failed',
  '重命名': 'Rename',
  '归档': 'Archive',
  '取消置顶': 'Unpin',
  '置顶任务': 'Pin Task',
  '操作失败，请重试。': 'Operation failed. Please try again.',
  '文件管理': 'File Management',
  '分享为图片': 'Share as Image',
  '长图已保存并复制到剪贴板': 'The long image has been saved and copied to the clipboard',
  '生成分享图片失败，请重试。': 'Failed to generate the shared image. Please try again.',
  '导出 Markdown': 'Export Markdown',
  '已导出任务记录': 'Task record exported',
  '导出失败，请重试。': 'Export failed. Please try again.',
  '审批失败，请重试。': 'Approval failed. Please try again.',
  '结束操控失败，请重试。': 'Failed to end control. Please try again.',
  '工作区导航': 'Workspace navigation',
  '收起侧栏': 'Collapse sidebar',
  '项目与任务': 'Projects and tasks',
  '请在桌面应用中添加项目': 'Please add projects in the desktop app',
  '在 {name} 中新建任务': 'New task in {name}',
  '{name} 更多操作': 'More actions for {name}',
  '等待审批': 'Waiting for approval',
  '等待补充信息': 'Waiting for more information',
  '{title} 更多操作': 'More actions for {title}',
  '暂无任务': 'No tasks yet',
  '打开本地文件夹，': 'Open a local folder',
  '在这里管理你的项目。': 'and manage your projects here.',
  '设置': 'Settings',
  '本地工作区': 'Local workspace',
  '展开侧栏': 'Expand sidebar',
  '工作模式': 'Work mode',
  'Code：对话式编码': 'Code: Conversational coding',
  'Work：画布工作流': 'Work: Canvas workflow',
  '浏览器预览': 'Browser preview',
  '切换到浅色': 'Switch to light',
  '切换到深色': 'Switch to dark',
  '任务操作': 'Task actions',
  '收回任务面板': 'Dock task panel',
  '收起右栏': 'Collapse right panel',
  '展开右栏': 'Expand right panel',
  '还原': 'Restore',
  '最大化': 'Maximize',
  '正在操控电脑': 'Controlling the computer',
  '正在操控浏览器': 'Controlling the browser',
  '结束操控': 'End control',
  '保存设置失败，请重试。': 'Failed to save settings. Please try again.',
  '正在思考…': 'Thinking…',
  '加载更早的 {n} 条消息': 'Load {n} earlier messages',
  '上一页': 'Previous page',
  '下一页': 'Next page',
  '消息导航': 'Message navigation',
  '（无文本）': '(no text)',
  '助手请求：{summary}': 'Assistant request: {summary}',
  '将修改项目中的文件': 'Will modify files in the project',
  '将在项目目录中执行命令': 'Will run a command in the project directory',
  '将提交当前改动并推送到 GitHub 仓库': 'Will commit current changes and push to the GitHub repository',
  '将操控你的鼠标、键盘或读取屏幕，请确认后再批准': 'Will control your mouse, keyboard, or read the screen — please confirm before approving',
  '将调用第三方插件，插件可访问项目目录': 'Will call a third-party plugin that can access the project directory',
  '将调用外部 MCP 服务器提供的工具': 'Will call a tool provided by an external MCP server',
  '将在隔离的浏览器会话中打开网页': 'Will open a web page in an isolated browser session',
  '拒绝': 'Reject',
  '批准': 'Approve',
  '准备好，开始新的会话。': 'Ready to start a new session.',
  '从一个项目开始。': 'Start with a project.',
  '在 {name} 中与 Cubex 协作：读代码、改文件、跑命令。': 'Collaborate with Cubex in {name}: read code, edit files, run commands.',
  '打开你的项目，让思路在这里继续。': 'Open your project and let your ideas continue here.',
  '排队消息': 'Queued messages',
  '移除排队消息': 'Remove queued message',
  '任务待办进度 {done}/{total}': 'Task to-do progress {done}/{total}',
  '{index}. {content}（{status}）': '{index}. {content} ({status})',
  '进行中': 'In progress',
  '待办': 'To do',
  '第 {index} 项：{content}': 'Item {index}: {content}',
  '待发送图片': 'Images to send',
  '图片 {index}': 'Image {index}',
  '移除图片': 'Remove image',
  '消息': 'Message',
  '继续输入，发送后将排队等待当前回复结束…': 'Keep typing — after sending, it will queue until the current reply finishes…',
  '描述你想做的事，Ctrl Enter 发送，Enter 换行…': 'Describe what you want to do. Ctrl Enter to send, Enter for a new line…',
  '描述你想做的事，Enter 发送，Shift Enter 换行…': 'Describe what you want to do. Enter to send, Shift Enter for a new line…',
  '选择项目后开始会话…': 'Select a project to start a conversation…',
  '选择项目 · Ctrl O': 'Select project · Ctrl O',
  '本机目录仅在桌面应用中可用': 'Local directories are only available in the desktop app',
  '选择项目': 'Select project',
  '模型': 'Model',
  '输入工具': 'Input tools',
  '添加文件': 'Add file',
  '添加项目文件到消息': 'Add a project file to the message',
  '添加图片': 'Add image',
  '添加图片（可粘贴或拖拽）': 'Add image (paste or drag & drop)',
  '停止语音输入': 'Stop voice input',
  '正在下载语音模型 {progress}%': 'Downloading speech model {progress}%',
  '正在识别语音…': 'Transcribing…',
  '语音输入': 'Voice input',
  '技能与 MCP': 'Skills & MCP',
  '技能与 MCP（在设置中管理）': 'Skills & MCP (manage in Settings)',
  '加入队列': 'Add to queue',
  '加入队列，当前回复结束后发送': 'Add to queue; sent after the current reply finishes',
  '停止回复': 'Stop reply',
  '发送': 'Send',
  '发送 · {key}': 'Send · {key}',
  '预览模式 · 会话与模型调用需在桌面应用中使用': 'Preview mode · Conversations and model calls require the desktop app',
  '尚未配置模型，先到设置中添加提供商与模型。': 'No model configured yet. Add a provider and model in Settings first.',
  '回复进行中 · 可继续输入补充说明，发送后自动排队': 'Reply in progress · You can keep typing to add details; sending will queue it automatically',
  '助手需要更多信息': 'The assistant needs more information',
  '助手需要你补充信息': 'The assistant needs more information from you',
  '停止本次任务': 'Stop this task',
  '回答': 'Answer',
  '可多选上方选项，也可在此补充说明…': 'Select multiple options above, or add details here…',
  '或在此直接输入其他回答…': 'Or type a different answer here…',
  '输入你的回答，Enter 提交，Shift Enter 换行…': 'Type your answer. Enter to submit, Shift Enter for a new line…',
  '提交回答': 'Submit answer',
  '思考中': 'Thinking',
  '规划下一步': 'Planning next step',
  '撰写回复': 'Writing reply',
  '执行工具': 'Running tool',
  '协调子智能体': 'Coordinating sub-agents',
  '等待中': 'Waiting',
  ' · 第 {step} 步': ' · Step {step}',
  '工作流 · 共 {steps} 步': 'Workflow · {steps} step(s)',
  '回退到此消息之前': 'Roll back to before this message',
  '删除此消息': 'Delete this message',
  '正在生成…': 'Generating…',
  '重新生成': 'Regenerate',
  '已拒绝': 'Denied',
  '完成': 'Done',
  '失败': 'Failed',
  '截图': 'Screenshot',
  '更多操作': 'More actions',
}

const morePhrases: Record<string, string> = {
  '简体中文': 'Simplified Chinese',
  '跟随提问语言': 'Follow question language',
  '简洁': 'Concise',
  '适中': 'Balanced',
  '详细': 'Detailed',
  '深色': 'Dark',
  '浅色': 'Light',
  '跟随系统': 'Follow system',
  '抹茶绿': 'Matcha green',
  '海洋蓝': 'Ocean blue',
  '日落橙': 'Sunset orange',
  '薰衣紫': 'Lavender',
  '胭脂粉': 'Rouge pink',
  '极简灰': 'Minimal gray',
  '系统默认': 'System default',
  '现代黑体 (Inter)': 'Modern sans (Inter)',
  '无衬线 · Inter': 'Sans-serif · Inter',
  '无衬线 · Roboto': 'Sans-serif · Roboto',
  '无衬线 · 系统 UI': 'Sans-serif · System UI',
  '衬线宋体': 'Serif · Song',
  '衬线 · Georgia': 'Serif · Georgia',
  '衬线 · Source Serif': 'Serif · Source Serif',
  '圆润 · Nunito': 'Rounded · Nunito',
  '中文 · 微软雅黑': 'Chinese · Microsoft YaHei',
  '中文 · 苹方': 'Chinese · PingFang',
  '中文黑体 · 思源黑体': 'Chinese sans · Source Han Sans',
  '中文宋体 · 思源宋体': 'Chinese serif · Source Han Serif',
  '中文 · 楷体': 'Chinese · Kaiti',
  '等宽 · Cascadia': 'Monospace · Cascadia',
  '等宽 · JetBrains Mono': 'Monospace · JetBrains Mono',
  '舒适': 'Comfortable',
  '紧凑': 'Compact',
  '自动（Windows 用 PowerShell）': 'Auto (PowerShell on Windows)',
  'Enter 发送，Shift+Enter 换行': 'Enter to send, Shift+Enter for a new line',
  'Ctrl+Enter 发送，Enter 换行': 'Ctrl+Enter to send, Enter for a new line',
  '语言': 'Language',
  '界面语言、回复语言与回复风格': 'Interface language, reply language, and reply style',
  '深色、浅色、配色方案与自定义背景': 'Dark, light, color scheme, and custom background',
  '查看并恢复已归档的项目': 'View and restore archived projects',
  '权限审批': 'Permissions & approval',
  '审批模式、只读与命令规则': 'Approval mode, read-only, and command rules',
  '外部工具服务器（Model Context Protocol）': 'External tool servers (Model Context Protocol)',
  '提供商、模型、连接测试与单模型高级参数': 'Providers, models, connection tests, and per-model advanced parameters',
  '浏览器、电脑控制与自定义插件': 'Browser, computer control, and custom plugins',
  '访问令牌、目标仓库与自动推送': 'Access token, target repository, and auto-push',
  '按间隔或每天/每周定时自动执行的任务': 'Tasks that run automatically at an interval or daily/weekly',
  'Work 模式': 'Work mode',
  '工作流运行方式与电脑/浏览器操控': 'How workflows run and computer/browser control',
  '完成、等待审批与等待输入时的提示音': 'Sounds for completion, awaiting approval, and awaiting input',
  '工作树': 'Worktree',
  '命令执行环境与改动验证': 'Command execution environment and change verification',
  '规则与记忆': 'Rules & memory',
  '项目上下文文件、计划方式与跨应用交接': 'Project context files, planning, and cross-app handoff',
  '外观': 'Appearance',
  '字号、密度、动效与对话显示': 'Font size, density, motion, and chat display',
  '主题、配色、背景、字号、密度、动效与对话显示': 'Theme, colors, background, font size, density, motion, and chat display',
  '键盘快捷键': 'Keyboard shortcuts',
  '发送方式与常用快捷键': 'Send method and common shortcuts',
  '关于': 'About',
  '版本与数据位置': 'Version and data location',
  '每 30 分钟': 'Every 30 min',
  '每小时': 'Hourly',
  '每 3 小时': 'Every 3 hours',
  '每 12 小时': 'Every 12 hours',
  '每天': 'Daily',
  '每周': 'Weekly',
  '打开项目文件夹': 'Open project folder',
  '打开 / 关闭设置': 'Open / close settings',
  '换行 / 发送（取决于下方发送方式）': 'New line / send (depends on the send method below)',
  '端点须为 HTTPS 或本机 HTTP 地址，且不能包含凭据、查询参数或片段': 'The endpoint must be an HTTPS or local HTTP address without credentials, query parameters, or fragments',
  '温度不能小于 0': 'Temperature cannot be less than 0',
  '温度不能大于 2': 'Temperature cannot be greater than 2',
  '不能为负数': 'Cannot be negative',
  '最多 200000': 'At most 200000',
  '至少 10 秒': 'At least 10 seconds',
  '最多 900 秒': 'At most 900 seconds',
  '最多 5 次': 'At most 5 times',
  '至少 10 条': 'At least 10 items',
  '最多 400 条': 'At most 400 items',
  '最多 4000 字': 'At most 4000 characters',
  '规则不能为空': 'The rule cannot be empty',
  '仅支持 png / jpeg / gif / webp 图片': 'Only png / jpeg / gif / webp images are supported',
  '字号最小 12': 'Minimum font size is 12',
  '字号最大 18': 'Maximum font size is 18',
  '代码字号最小 11': 'Minimum code font size is 11',
  '代码字号最大 18': 'Maximum code font size is 18',
  '至少 1 步': 'At least 1 step',
  '最多 200 步': 'At most 200 steps',
  '至少 5 秒': 'At least 5 seconds',
  '最多 1800 秒': 'At most 1800 seconds',
  '最多 100 条': 'At most 100 items',
  '格式应为 仓库名 或 用户名/仓库名': 'The format should be repo or owner/repo',
  '分支不能为空': 'The branch cannot be empty',
  '分支名只能包含字母、数字、. _ / -': 'The branch name may only contain letters, numbers, . _ / -',
  '名称不能为空': 'The name cannot be empty',
  '名称只能包含字母、数字、_ . -': 'The name may only contain letters, numbers, _ . -',
  '启动命令不能为空': 'The start command cannot be empty',
  'MCP 服务器名称必须唯一': 'MCP server names must be unique',
  '间隔至少 10 分钟': 'The interval must be at least 10 minutes',
  '间隔最多 7 天': 'The interval must be at most 7 days',
  '时间格式应为 HH:MM': 'The time format should be HH:MM',
  '每周执行至少选择一天': 'Select at least one day for weekly execution',
  '指令不能为空（或改为选择工作流）': 'The instruction cannot be empty (or choose a workflow instead)',
  '提供商标识必须唯一': 'Provider identifiers must be unique',
  '模型标识必须唯一': 'Model identifiers must be unique',
  '模型引用的提供商不存在': 'The provider referenced by the model does not exist',
  '默认模型不存在': 'The default model does not exist',
  '单个工作流最多 20 个节点': 'A single workflow can have at most 20 nodes',
  '请输入内容或添加图片': 'Please enter content or add an image',
  '工具名只能包含字母、数字、_ -': 'The tool name may only contain letters, numbers, _ -',
  '插件名只能包含字母、数字、_ -': 'The plugin name may only contain letters, numbers, _ -',
  'OpenAI 兼容': 'OpenAI-compatible',
  'Ollama（本机）': 'Ollama (local)',
  '逐项确认': 'Confirm each',
  '写文件与执行命令都需要你批准': 'Writing files and running commands both require your approval',
  '自动编辑': 'Auto-edit',
  '自动写文件，执行命令需要批准': 'Write files automatically; running commands requires approval',
  '完全自动': 'Fully automatic',
  '文件与命令都自动执行；文件操作限制在项目目录内，命令不受沙箱限制，请谨慎使用': 'Files and commands run automatically; file operations are limited to the project directory, commands are not sandboxed — use with caution',
}

const settingsPhrases2: Record<string, string> = {
  '设置分类': 'Settings categories',
  '返回会话': 'Back to chat',
  '搜索设置': 'Search settings',
  '没有找到与“{query}”相关的设置': 'No settings found for “{query}”',
  '有 {count} 处设置需要修正，已在对应位置标出': '{count} setting(s) need fixing, marked in place',
  '正在自动保存…': 'Saving…',
  '改动将自动保存…': 'Changes will be saved automatically…',
  '已自动保存并生效': 'Saved and applied automatically',
  '改动会自动保存并立即生效': 'Changes are saved automatically and take effect immediately',
  '提供商': 'Provider',
  '添加提供商': 'Add provider',
  '尚未配置提供商。添加后填写端点与 API Key。': 'No providers yet. Add one, then fill in the endpoint and API key.',
  '未命名提供商': 'Untitled provider',
  '本机': 'Local',
  '已配置 Key': 'Key configured',
  '待保存 Key': 'Key pending',
  '未配置 Key': 'No key',
  '端点': 'Endpoint',
  'HTTPS 或本机 HTTP': 'HTTPS or local HTTP',
  '通常以 /v1 结尾，程序会自动拼接 /chat/completions': 'Usually ends with /v1; /chat/completions is appended automatically',
  '已加密保存，输入新值可替换': 'Saved (encrypted); enter a new value to replace',
  '保存 Key': 'Save key',
  '点击“保存 Key”立即生效': 'Click “Save key” to apply immediately',
  '点击底部“保存”时会一并加密保存': 'Encrypted and saved together when you click “Save” at the bottom',
  '删除提供商': 'Delete provider',
  '{count} / 60 · 默认模型用于新会话': '{count} / 60 · Default model is used for new sessions',
  '添加模型': 'Add model',
  '请先添加提供商。': 'Add a provider first.',
  '尚未配置模型。': 'No models configured yet.',
  '未命名模型': 'Untitled model',
  '提供商缺失': 'Provider missing',
  '连接正常': 'Connected',
  '默认': 'Default',
  '显示名称': 'Display name',
  '请选择': 'Please select',
  '模型 ID': 'Model ID',
  '如 gpt-4.1、claude-sonnet-4-5、qwen2.5-coder': 'e.g. gpt-4.1, claude-sonnet-4-5, qwen2.5-coder',
  '请填写服务商提供的模型 ID': 'Enter the model ID provided by your provider',
  '上下文窗口（可选）': 'Context window (optional)',
  '如 128000': 'e.g. 128000',
  '范围 4000–4000000 的整数': 'An integer between 4000 and 4000000',
  '高级': 'Advanced',
  '已覆盖 {count} 项': '{count} override(s)',
  '使用全局默认参数': 'Using global defaults',
  '留空的项沿用“全局默认参数”。': 'Empty fields fall back to the “global default parameters”.',
  '模型专属提示词（追加到系统提示末尾）': 'Model-specific prompt (appended to the end of the system prompt)',
  '如：该模型偏好简洁输出，请避免重复解释。': 'e.g. This model prefers concise output; avoid repeated explanations.',
  '正在测试连接…': 'Testing connection…',
  '（{ms} ms）': ' ({ms} ms)',
  '设为默认': 'Set as default',
  '删除模型': 'Delete model',
  '自动化': 'Automation',
  '添加自动化': 'Add automation',
  '请先打开一个项目，再为它添加自动化任务。': 'Open a project first, then add automation tasks for it.',
  '还没有自动化。可用于每日依赖检查、定时汇总 TODO、定期跑测试等。': 'No automations yet. Use them for daily dependency checks, scheduled TODO summaries, periodic test runs, and more.',
  '项目不存在': 'Project not found',
  '未命名自动化': 'Untitled automation',
  ' · 下次 {time}': ' · Next {time}',
  ' · 上次 {time}': ' · Last {time}',
  '使用默认模型': 'Use default model',
  '任务来源': 'Task source',
  '直接发送指令': 'Send instruction directly',
  '工作流不存在（请重选）': 'Workflow not found (please reselect)',
  '工作流：{name}': 'Workflow: {name}',
  '执行方式': 'Trigger type',
  '按间隔': 'By interval',
  '每天定时': 'Daily at time',
  '每周定时': 'Weekly at time',
  '执行间隔': 'Interval',
  '间隔分钟数': 'Interval minutes',
  '执行时间': 'Time',
  '执行日': 'Days',
  '附加指令（可选）': 'Additional instruction (optional)',
  '指令': 'Instruction',
  '已绑定工作流，将按工作流执行；此处留空即可，如需补充要求可填写': 'A workflow is bound and will be executed; leave this empty, or add extra requirements if needed',
  '例如：运行 npm test，若有失败则定位原因并给出修复建议，把结论追加到 memory.md': 'e.g. Run npm test; if it fails, find the cause, suggest fixes, and append the conclusion to memory.md',
  '启用自动化 {name}': 'Enable automation {name}',
  '请先保存设置': 'Save settings first',
  '立即运行': 'Run now',
  '每 {minutes} 分钟': 'Every {minutes} min',
  '周日': 'Sun',
  '周一': 'Mon',
  '周二': 'Tue',
  '周三': 'Wed',
  '周四': 'Thu',
  '周五': 'Fri',
  '周六': 'Sat',
  '每天 {time}': 'Daily {time}',
  '每周{label} {time}': 'Weekly {label} {time}',
  '关闭提示': 'Dismiss',
  '取消': 'Cancel',
  '确定': 'OK',
  '未选择': 'Not selected',
  '暂无可选项': 'No options available',
  '复制代码': 'Copy code',
}

const skillPhrases: Record<string, string> = {
  '技能': 'Skills',
  '内置': 'Built-in',
  '↑↓ 选择 · Enter 确认 · Esc 取消': '↑↓ to move · Enter to confirm · Esc to cancel',
  '未找到匹配的技能，可在设置中导入': 'No matching skill found — import one in Settings',
  '（输入 / 调用技能）': ' (type / to use a skill)',
  '上传技能文件，用 / 名称在对话中快速调用': 'Upload skill files and call them with / name in chat',
  '上传 Markdown / 文本技能文件，在对话输入框用 / 名称即可调用其内容': 'Upload Markdown / text skill files, then type / name in the composer to insert them',
  '打开技能目录': 'Open skills folder',
  '导入技能': 'Import skills',
  '支持 .md / .markdown / .txt；可用 YAML 头（name、description）自定义名称与说明。在对话输入框输入 / 加名称即可调用。': 'Supports .md / .markdown / .txt; use a YAML header (name, description) to customize. Type / plus the name in the composer to use it.',
  '正在读取技能…': 'Loading skills…',
  '还没有技能，点击“导入技能”添加文件': 'No skills yet — click "Import skills" to add files',
  '预览': 'Preview',
  '收起': 'Collapse',
  '删除技能 {name}': 'Delete skill {name}',
}

const workflowPhrases: Record<string, string> = {
  '工作流进度': 'Workflow progress',
  '运行中': 'Running',
  '已暂停': 'Paused',
  '已完成': 'Completed',
  '步骤 {i}/{n}': 'Step {i}/{n}',
  '完成 {done}/{n}': 'Done {done}/{n}',
  '暂停': 'Pause',
  '继续': 'Resume',
  '重试该步骤': 'Retry this step',
  '跳过该步骤': 'Skip this step',
  '失败原因：{error}': 'Reason: {error}',
  '工作流操作失败，请重试。': 'Workflow action failed, please try again.',
}

registerPhrases(phrases)
registerPhrases(settingsPhrases)
registerPhrases(appPhrases)
registerPhrases(morePhrases)
registerPhrases(settingsPhrases2)
registerPhrases(skillPhrases)
registerPhrases(workflowPhrases)

export {}
